name: Snyk SCA Scan

permissions:
  contents: read
  security-events: write
  
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # - name: Run Snyk to test for vulnerabilities
      #   uses: snyk/actions/node@master
      #   with:
      #     command: test
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test and generate reports
        run: |
          npx snyk test --json-file-output=snyk-results.json || true
          npx snyk test --sarif-file-output=snyk-results.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Convert Snyk JSON to HTML
        run: |
          npx snyk-to-html -i snyk-results.json -o snyk-results.html
    
      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-results.sarif

      - name: Upload raw Snyk HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sca-report
          path: snyk-results.html
